/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PaintingsIndexImport } from './routes/paintings/index'
import { Route as PaintingsTitleImport } from './routes/paintings/$title'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PaintingsIndexRoute = PaintingsIndexImport.update({
  id: '/paintings/',
  path: '/paintings/',
  getParentRoute: () => rootRoute,
} as any)

const PaintingsTitleRoute = PaintingsTitleImport.update({
  id: '/paintings/$title',
  path: '/paintings/$title',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/paintings/$title': {
      id: '/paintings/$title'
      path: '/paintings/$title'
      fullPath: '/paintings/$title'
      preLoaderRoute: typeof PaintingsTitleImport
      parentRoute: typeof rootRoute
    }
    '/paintings/': {
      id: '/paintings/'
      path: '/paintings'
      fullPath: '/paintings'
      preLoaderRoute: typeof PaintingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paintings/$title': typeof PaintingsTitleRoute
  '/paintings': typeof PaintingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paintings/$title': typeof PaintingsTitleRoute
  '/paintings': typeof PaintingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/paintings/$title': typeof PaintingsTitleRoute
  '/paintings/': typeof PaintingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/paintings/$title' | '/paintings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/paintings/$title' | '/paintings'
  id: '__root__' | '/' | '/paintings/$title' | '/paintings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaintingsTitleRoute: typeof PaintingsTitleRoute
  PaintingsIndexRoute: typeof PaintingsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaintingsTitleRoute: PaintingsTitleRoute,
  PaintingsIndexRoute: PaintingsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/paintings/$title",
        "/paintings/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/paintings/$title": {
      "filePath": "paintings/$title.tsx"
    },
    "/paintings/": {
      "filePath": "paintings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
